export const SUPPORTED_LANGUAGES = ['en', 'cs', 'de', 'es', 'fr'];

export const LANGUAGE_LABELS = {
  en: 'EN', cs: 'CZ', de: 'DE', es: 'ES', fr: 'FR'
};

const messages = {
  en: {
    sources: 'Sources', tools: 'Tools', support: 'Support', browseSources: 'Browse sources', buildSource: 'Build my Source', openConverter: 'Open DEB → IPA Converter',
    heroTitle: 'iOS sources. Catalog. Tools.', heroDesc: 'A live catalog of checked AltStore, SideStore and LiveContainer sources. Filter by source type and content, combine compatible sources and use practical iOS tools directly in the browser.',
    availableSources: 'available sources', mixReadySources: 'mix-ready sources', discoveredApps: 'unique discovered apps',
    catalogTitle: 'AltStore · SideStore · LiveContainer sources', catalogDesc: 'Only sources that passed the latest automated availability and JSON check are shown.',
    sourceType: 'Source type', genre: 'Genre', search: 'Search', sort: 'Sort', sortName: 'Name A–Z', sortAppsHigh: 'Apps: most first', sortAppsLow: 'Apps: fewest first', reportBug: 'Report a bug', selection: 'Selection', all: 'All', official: 'Official', trusted: 'Trusted', community: 'Community', modified: 'Modified',
    games: 'Games', emulators: 'Emulators', video: 'Video', music: 'Music', animeManga: 'Anime & Manga', social: 'Social', downloads: 'Downloads', sideloadTools: 'Sideload Tools', utilities: 'Utilities',
    searchPlaceholder: 'Search sources…', note: 'Note:', catalogNote: 'CaseyCZ iOS Hub does not rehost third-party IPA files. The catalog uses original public source URLs and preserves original download links. External sources can change at any time.',
    toolsTitle: 'Tools', toolsDesc: 'Utilities that run directly in your browser and work on iPhone, iPad, Mac and PC.', readySourcesTitle: 'Ready sources', readySourcesDesc: 'Use a prepared CaseyCZ source or open the standalone Custom Builder for your own filtered Mix.', customBuilderCardTitle: 'Custom Builder', customBuilderCardDesc: 'Filter checked sources, choose any combination and create your own CaseyCZ Mix on a dedicated page.', openBuilder: 'Open Builder', converterCardTitle: 'DEB → IPA Converter', converterCardDesc: 'Convert a compatible iOS .deb package to .ipa locally in your browser. Packages with special filesystem metadata may still require a desktop conversion tool.', openTool: 'Open tool',
    supportEyebrow: 'SUPPORT CASEYCZ', supportTitle: 'Support further development.', supportDesc: 'If CaseyCZ iOS Hub saves you time, you can support further development through Buy Me a Coffee.', openCoffee: 'Open Buy Me a Coffee ↗',
    nothingFound: 'Nothing found', tryFilters: 'Try another source type, genre or search term.', online: 'Online', apps: 'apps', checked: 'Checked', showApps: 'Show included apps', noApps: 'No apps listed in this source.', add: '＋ Add', copied: 'Copied.', sourceCopied: 'Source URL copied.', copyUrl: 'Copy URL', catalogLoadError: 'Could not load the source catalog.',
    converterIntro: 'Convert an iOS application from a .deb package to .ipa directly in your browser. Works on Windows, macOS and iPhone — your file is never uploaded.', local100: '100% local', noUpload: 'No upload', chooseDeb: 'Choose a .deb file', chooseDebHelp: 'It must contain an actual iOS .app application.', dropDeb: 'Drop .deb here', tapChoose: 'or tap to choose a file', largeIphone: 'Large file on iPhone:', largeIphoneDesc: 'Safari has limited working memory. Very large .deb files may be more reliable on Mac or PC.', convertToIpa: 'Convert to IPA', preparing: 'Preparing conversion…', done: 'DONE', downloadIpa: 'Download IPA', shareIpa: 'Share IPA', convertAnother: 'Convert another', conversionFailed: 'Conversion failed', tryAgain: 'Try again', whatWebDoes: 'What the web app does', stepDeb: 'Opens the Debian .deb / AR package.', stepData: 'Finds data.tar and the actual .app inside.', stepPayload: 'Creates the required Payload/App.app structure.', stepIpa: 'Packages the result as .ipa.', important: 'Important:', importantDesc: 'Only .deb packages containing an .app can be converted. Jailbreak tweaks, libraries and system packages cannot become an IPA by repackaging alone.', signing: 'Signing:', signingDesc: 'The resulting IPA is not automatically signed. Install it afterwards using AltStore, SideStore, LiveContainer or another compatible installer.', loadingEngine: 'Loading conversion engine…', engineReady: 'Conversion engine ready.', openingDeb: 'Opening DEB…', extractingDeb: 'Extracting Debian package…', dataFound: 'Data archive found…', lookingApp: 'Looking for iOS application…', buildingPayload: 'Building Payload…', packagingIpa: 'Packaging IPA…', packagingWait: 'This can take a while for a large app.', processedLocal: 'processed locally', appFiles: 'app files', files: 'files', shareFailed: 'Sharing failed.', chooseDebToast: 'Choose a .deb file.', debInvalid: 'The package does not look like a standard Debian .deb — data.tar.* was not found.', appNotFound: 'No iOS .app was found in the package. Tweaks, libraries and other Debian packages cannot be converted to IPA.'
  },
  cs: {
    sources: 'Zdroje', tools: 'Nástroje', support: 'Podpořit', browseSources: 'Procházet zdroje', buildSource: 'Vytvořit vlastní Source', openConverter: 'Otevřít DEB → IPA převodník',
    heroTitle: 'iOS zdroje. Katalog. Nástroje.', heroDesc: 'Živý katalog kontrolovaných zdrojů pro AltStore, SideStore a LiveContainer. Filtruj podle typu zdroje a obsahu, spojuj kompatibilní zdroje a používej praktické iOS nástroje přímo v prohlížeči.',
    availableSources: 'dostupných zdrojů', mixReadySources: 'zdroje pro Mix', discoveredApps: 'unikátních nalezených aplikací',
    catalogTitle: 'AltStore · SideStore · LiveContainer zdroje', catalogDesc: 'Zobrazují se pouze zdroje, které prošly poslední automatickou kontrolou dostupnosti a JSONu.',
    sourceType: 'Typ zdroje', genre: 'Žánr', search: 'Hledání', sort: 'Řazení', sortName: 'Název A–Z', sortAppsHigh: 'Aplikace: nejvíce', sortAppsLow: 'Aplikace: nejméně', reportBug: 'Nahlásit chybu', selection: 'Výběr', all: 'Vše', official: 'Official', trusted: 'Trusted', community: 'Community', modified: 'Modified',
    games: 'Hry', emulators: 'Emulátory', video: 'Video', music: 'Hudba', animeManga: 'Anime & Manga', social: 'Sociální', downloads: 'Stahování', sideloadTools: 'Sideload nástroje', utilities: 'Utility',
    searchPlaceholder: 'Hledat zdroje…', note: 'Poznámka:', catalogNote: 'CaseyCZ iOS Hub nerehostuje cizí IPA soubory. Katalog používá původní veřejné source URL a zachovává originální download odkazy. Externí zdroje mohou svůj obsah kdykoliv změnit.',
    toolsTitle: 'Nástroje', toolsDesc: 'Utility běžící přímo v prohlížeči na iPhonu, iPadu, Macu i PC.', readySourcesTitle: 'Hotové zdroje', readySourcesDesc: 'Použij připravený CaseyCZ zdroj nebo otevři samostatný Custom Builder pro vlastní filtrovaný Mix.', customBuilderCardTitle: 'Custom Builder', customBuilderCardDesc: 'Filtruj kontrolované zdroje, vyber libovolnou kombinaci a vytvoř vlastní CaseyCZ Mix na samostatné stránce.', openBuilder: 'Otevřít Builder', converterCardTitle: 'DEB → IPA převodník', converterCardDesc: 'Převeď kompatibilní iOS .deb na .ipa lokálně v prohlížeči. Balíčky se speciálními filesystem metadaty mohou stále vyžadovat desktopový nástroj.', openTool: 'Otevřít nástroj',
    supportEyebrow: 'PODPORA CASEYCZ', supportTitle: 'Podpořit další vývoj.', supportDesc: 'Pokud ti CaseyCZ iOS Hub šetří čas, můžeš podpořit další vývoj přes Buy Me a Coffee.', openCoffee: 'Otevřít Buy Me a Coffee ↗',
    nothingFound: 'Nic nenalezeno', tryFilters: 'Zkus jiný typ zdroje, žánr nebo hledaný výraz.', online: 'Online', apps: 'aplikací', checked: 'Kontrola', showApps: 'Zobrazit obsažené aplikace', noApps: 'V tomto zdroji nejsou uvedené žádné aplikace.', add: '＋ Přidat', copied: 'Zkopírováno.', sourceCopied: 'URL zdroje zkopírována.', copyUrl: 'Kopírovat URL', catalogLoadError: 'Nepodařilo se načíst katalog zdrojů.',
    converterIntro: 'Převeď iOS aplikaci z balíčku .deb na .ipa přímo v prohlížeči. Funguje na Windows, macOS i iPhonu — soubor se nikam neodesílá.', local100: '100 % lokálně', noUpload: 'Bez uploadu', chooseDeb: 'Vyber .deb soubor', chooseDebHelp: 'Musí obsahovat skutečnou iOS .app aplikaci.', dropDeb: 'Přetáhni .deb sem', tapChoose: 'nebo klepni a vyber soubor', largeIphone: 'Velký soubor na iPhonu:', largeIphoneDesc: 'Safari má omezenou operační paměť. U velmi velkých .deb může být spolehlivější Mac nebo PC.', convertToIpa: 'Převést na IPA', preparing: 'Připravuji převod…', done: 'HOTOVO', downloadIpa: 'Stáhnout IPA', shareIpa: 'Sdílet IPA', convertAnother: 'Převést další', conversionFailed: 'Převod se nepodařil', tryAgain: 'Zkusit znovu', whatWebDoes: 'Co web udělá', stepDeb: 'Rozbalí Debian .deb / AR balíček.', stepData: 'Najde data.tar a uvnitř skutečnou .app.', stepPayload: 'Vytvoří správnou strukturu Payload/App.app.', stepIpa: 'Zabalí výsledek jako .ipa.', important: 'Důležité:', importantDesc: 'Funguje jen pro .deb obsahující aplikaci .app. Jailbreak tweaky, knihovny a systémové balíčky nelze pouhým přebalením změnit na IPA.', signing: 'Podepisování:', signingDesc: 'Výsledná IPA není automaticky podepsaná. Pro instalaci ji následně použij v AltStore, SideStore, LiveContainer nebo jiném kompatibilním instalačním nástroji.', loadingEngine: 'Načítám převodní engine…', engineReady: 'Převodní engine připraven.', openingDeb: 'Otevírám DEB…', extractingDeb: 'Rozbaluji Debian balíček…', dataFound: 'Našel jsem data archiv…', lookingApp: 'Hledám iOS aplikaci…', buildingPayload: 'Vytvářím Payload…', packagingIpa: 'Balím IPA…', packagingWait: 'Tohle může u velké aplikace chvíli trvat.', processedLocal: 'zpracováno lokálně', appFiles: 'souborů v aplikaci', files: 'souborů', shareFailed: 'Sdílení se nepodařilo.', chooseDebToast: 'Vyber soubor s příponou .deb.', debInvalid: 'Balíček nevypadá jako standardní Debian .deb — nenašel jsem data.tar.*.', appNotFound: 'V balíčku jsem nenašel iOS aplikaci .app. Tweaky, knihovny a jiné Debian balíčky nelze převést na IPA.'
  },
  de: {
    sources: 'Quellen', tools: 'Werkzeuge', support: 'Unterstützen', browseSources: 'Quellen durchsuchen', buildSource: 'Eigene Source erstellen', openConverter: 'DEB → IPA Konverter öffnen',
    heroTitle: 'iOS-Quellen. Katalog. Werkzeuge.', heroDesc: 'Ein laufend geprüfter Katalog für AltStore-, SideStore- und LiveContainer-Quellen. Nach Quellentyp und Inhalt filtern, kompatible Quellen kombinieren und praktische iOS-Werkzeuge direkt im Browser nutzen.',
    availableSources: 'verfügbare Quellen', mixReadySources: 'Mix-fähige Quellen', discoveredApps: 'eindeutige gefundene Apps',
    catalogTitle: 'AltStore · SideStore · LiveContainer Quellen', catalogDesc: 'Es werden nur Quellen angezeigt, die die letzte automatische Verfügbarkeits- und JSON-Prüfung bestanden haben.',
    sourceType: 'Quellentyp', genre: 'Kategorie', search: 'Suche', sort: 'Sortieren', sortName: 'Name A–Z', sortAppsHigh: 'Apps: meiste zuerst', sortAppsLow: 'Apps: wenigste zuerst', reportBug: 'Fehler melden', selection: 'Auswahl', all: 'Alle', official: 'Offiziell', trusted: 'Vertrauenswürdig', community: 'Community', modified: 'Modifiziert',
    games: 'Spiele', emulators: 'Emulatoren', video: 'Video', music: 'Musik', animeManga: 'Anime & Manga', social: 'Social', downloads: 'Downloads', sideloadTools: 'Sideload-Tools', utilities: 'Werkzeuge',
    searchPlaceholder: 'Quellen suchen…', note: 'Hinweis:', catalogNote: 'CaseyCZ iOS Hub hostet keine fremden IPA-Dateien. Der Katalog nutzt die ursprünglichen öffentlichen Source-URLs und Download-Links. Externe Quellen können sich jederzeit ändern.',
    toolsTitle: 'Werkzeuge', toolsDesc: 'Browser-Werkzeuge für iPhone, iPad, Mac und PC.', readySourcesTitle: 'Fertige Quellen', readySourcesDesc: 'Nutze eine vorbereitete CaseyCZ-Quelle oder öffne den eigenständigen Custom Builder für deinen eigenen gefilterten Mix.', customBuilderCardTitle: 'Custom Builder', customBuilderCardDesc: 'Filtere geprüfte Quellen, wähle eine beliebige Kombination und erstelle deinen eigenen CaseyCZ Mix auf einer eigenen Seite.', openBuilder: 'Builder öffnen', converterCardTitle: 'DEB → IPA Konverter', converterCardDesc: 'Konvertiert kompatible iOS-.deb-Pakete lokal im Browser zu .ipa. Pakete mit speziellen Dateisystem-Metadaten können weiterhin ein Desktop-Werkzeug benötigen.', openTool: 'Werkzeug öffnen',
    supportEyebrow: 'CASEYCZ UNTERSTÜTZEN', supportTitle: 'Weitere Entwicklung unterstützen.', supportDesc: 'Wenn dir CaseyCZ iOS Hub hilft, kannst du die weitere Entwicklung über Buy Me a Coffee unterstützen.', openCoffee: 'Buy Me a Coffee öffnen ↗',
    nothingFound: 'Nichts gefunden', tryFilters: 'Versuche einen anderen Quellentyp, eine andere Kategorie oder Suche.', online: 'Online', apps: 'Apps', checked: 'Geprüft', showApps: 'Enthaltene Apps anzeigen', noApps: 'In dieser Quelle sind keine Apps aufgeführt.', add: '＋ Hinzufügen', copied: 'Kopiert.', sourceCopied: 'Source-URL kopiert.', copyUrl: 'URL kopieren', catalogLoadError: 'Der Quellenkatalog konnte nicht geladen werden.',
    converterIntro: 'Konvertiere eine iOS-App direkt im Browser von .deb zu .ipa. Funktioniert unter Windows, macOS und auf dem iPhone — die Datei wird nie hochgeladen.', local100: '100 % lokal', noUpload: 'Kein Upload', chooseDeb: '.deb-Datei wählen', chooseDebHelp: 'Sie muss eine echte iOS-.app enthalten.', dropDeb: '.deb hier ablegen', tapChoose: 'oder tippen und Datei wählen', largeIphone: 'Große Datei auf dem iPhone:', largeIphoneDesc: 'Safari hat begrenzten Arbeitsspeicher. Sehr große .deb-Dateien funktionieren auf Mac oder PC möglicherweise zuverlässiger.', convertToIpa: 'In IPA umwandeln', preparing: 'Konvertierung wird vorbereitet…', done: 'FERTIG', downloadIpa: 'IPA herunterladen', shareIpa: 'IPA teilen', convertAnother: 'Weitere konvertieren', conversionFailed: 'Konvertierung fehlgeschlagen', tryAgain: 'Erneut versuchen', whatWebDoes: 'Was das Tool macht', stepDeb: 'Öffnet das Debian-.deb-/AR-Paket.', stepData: 'Findet data.tar und die enthaltene .app.', stepPayload: 'Erstellt Payload/App.app.', stepIpa: 'Packt das Ergebnis als .ipa.', important: 'Wichtig:', importantDesc: 'Nur .deb-Pakete mit einer .app können konvertiert werden. Jailbreak-Tweaks, Bibliotheken und Systempakete lassen sich nicht einfach in IPA umpacken.', signing: 'Signierung:', signingDesc: 'Die erzeugte IPA ist nicht automatisch signiert. Installiere sie anschließend mit AltStore, SideStore, LiveContainer oder einem kompatiblen Installer.', loadingEngine: 'Konvertierungs-Engine wird geladen…', engineReady: 'Konvertierungs-Engine bereit.', openingDeb: 'DEB wird geöffnet…', extractingDeb: 'Debian-Paket wird entpackt…', dataFound: 'Datenarchiv gefunden…', lookingApp: 'iOS-App wird gesucht…', buildingPayload: 'Payload wird erstellt…', packagingIpa: 'IPA wird gepackt…', packagingWait: 'Bei großen Apps kann das etwas dauern.', processedLocal: 'lokal verarbeitet', appFiles: 'App-Dateien', files: 'Dateien', shareFailed: 'Teilen fehlgeschlagen.', chooseDebToast: 'Bitte eine .deb-Datei wählen.', debInvalid: 'Das Paket sieht nicht wie ein Standard-Debian-.deb aus — data.tar.* wurde nicht gefunden.', appNotFound: 'Keine iOS-.app im Paket gefunden. Tweaks, Bibliotheken und andere Debian-Pakete können nicht in IPA konvertiert werden.'
  },
  es: {
    sources: 'Fuentes', tools: 'Herramientas', support: 'Apoyar', browseSources: 'Explorar fuentes', buildSource: 'Crear mi Source', openConverter: 'Abrir conversor DEB → IPA',
    heroTitle: 'Fuentes iOS. Catálogo. Herramientas.', heroDesc: 'Un catálogo activo de fuentes verificadas para AltStore, SideStore y LiveContainer. Filtra por tipo y contenido, combina fuentes compatibles y usa herramientas iOS directamente en el navegador.',
    availableSources: 'fuentes disponibles', mixReadySources: 'fuentes para Mix', discoveredApps: 'apps únicas encontradas',
    catalogTitle: 'Fuentes AltStore · SideStore · LiveContainer', catalogDesc: 'Solo se muestran fuentes que superaron la última comprobación automática de disponibilidad y JSON.',
    sourceType: 'Tipo de fuente', genre: 'Género', search: 'Búsqueda', sort: 'Ordenar', sortName: 'Nombre A–Z', sortAppsHigh: 'Apps: más primero', sortAppsLow: 'Apps: menos primero', reportBug: 'Reportar un error', selection: 'Selección', all: 'Todo', official: 'Oficial', trusted: 'Confiable', community: 'Comunidad', modified: 'Modificado',
    games: 'Juegos', emulators: 'Emuladores', video: 'Vídeo', music: 'Música', animeManga: 'Anime y Manga', social: 'Social', downloads: 'Descargas', sideloadTools: 'Herramientas Sideload', utilities: 'Utilidades',
    searchPlaceholder: 'Buscar fuentes…', note: 'Nota:', catalogNote: 'CaseyCZ iOS Hub no realoja archivos IPA de terceros. El catálogo usa las URL públicas originales y conserva los enlaces de descarga originales. Las fuentes externas pueden cambiar en cualquier momento.',
    toolsTitle: 'Herramientas', toolsDesc: 'Utilidades que funcionan directamente en el navegador en iPhone, iPad, Mac y PC.', readySourcesTitle: 'Fuentes listas', readySourcesDesc: 'Usa una fuente CaseyCZ preparada o abre el Custom Builder independiente para crear tu propio Mix filtrado.', customBuilderCardTitle: 'Custom Builder', customBuilderCardDesc: 'Filtra fuentes comprobadas, elige cualquier combinación y crea tu propio CaseyCZ Mix en una página dedicada.', openBuilder: 'Abrir Builder', converterCardTitle: 'Conversor DEB → IPA', converterCardDesc: 'Convierte un paquete iOS .deb compatible a .ipa localmente en el navegador. Los paquetes con metadatos especiales del sistema de archivos pueden requerir una herramienta de escritorio.', openTool: 'Abrir herramienta',
    supportEyebrow: 'APOYAR CASEYCZ', supportTitle: 'Apoya el desarrollo.', supportDesc: 'Si CaseyCZ iOS Hub te resulta útil, puedes apoyar el desarrollo mediante Buy Me a Coffee.', openCoffee: 'Abrir Buy Me a Coffee ↗',
    nothingFound: 'No se encontraron resultados', tryFilters: 'Prueba otro tipo, género o búsqueda.', online: 'Online', apps: 'apps', checked: 'Comprobado', showApps: 'Mostrar apps incluidas', noApps: 'No hay apps listadas en esta fuente.', add: '＋ Añadir', copied: 'Copiado.', sourceCopied: 'URL de la fuente copiada.', copyUrl: 'Copiar URL', catalogLoadError: 'No se pudo cargar el catálogo.',
    converterIntro: 'Convierte una aplicación iOS de .deb a .ipa directamente en el navegador. Funciona en Windows, macOS y iPhone; el archivo nunca se sube.', local100: '100 % local', noUpload: 'Sin subida', chooseDeb: 'Elige un archivo .deb', chooseDebHelp: 'Debe contener una aplicación iOS .app real.', dropDeb: 'Suelta el .deb aquí', tapChoose: 'o toca para elegir un archivo', largeIphone: 'Archivo grande en iPhone:', largeIphoneDesc: 'Safari tiene memoria limitada. Los .deb muy grandes pueden funcionar mejor en Mac o PC.', convertToIpa: 'Convertir a IPA', preparing: 'Preparando conversión…', done: 'LISTO', downloadIpa: 'Descargar IPA', shareIpa: 'Compartir IPA', convertAnother: 'Convertir otro', conversionFailed: 'La conversión falló', tryAgain: 'Reintentar', whatWebDoes: 'Qué hace la herramienta', stepDeb: 'Abre el paquete Debian .deb / AR.', stepData: 'Encuentra data.tar y la .app real.', stepPayload: 'Crea Payload/App.app.', stepIpa: 'Empaqueta el resultado como .ipa.', important: 'Importante:', importantDesc: 'Solo se pueden convertir .deb que contengan una .app. Tweaks, bibliotecas y paquetes del sistema no se convierten en IPA solo reempaquetándolos.', signing: 'Firma:', signingDesc: 'La IPA resultante no se firma automáticamente. Instálala después con AltStore, SideStore, LiveContainer u otro instalador compatible.', loadingEngine: 'Cargando motor de conversión…', engineReady: 'Motor de conversión listo.', openingDeb: 'Abriendo DEB…', extractingDeb: 'Extrayendo paquete Debian…', dataFound: 'Archivo de datos encontrado…', lookingApp: 'Buscando aplicación iOS…', buildingPayload: 'Creando Payload…', packagingIpa: 'Empaquetando IPA…', packagingWait: 'Puede tardar con apps grandes.', processedLocal: 'procesado localmente', appFiles: 'archivos de la app', files: 'archivos', shareFailed: 'No se pudo compartir.', chooseDebToast: 'Elige un archivo .deb.', debInvalid: 'El paquete no parece un .deb Debian estándar: no se encontró data.tar.*.', appNotFound: 'No se encontró una .app de iOS. Tweaks, bibliotecas y otros paquetes Debian no se pueden convertir a IPA.'
  },
  fr: {
    sources: 'Sources', tools: 'Outils', support: 'Soutenir', browseSources: 'Parcourir les sources', buildSource: 'Créer ma Source', openConverter: 'Ouvrir le convertisseur DEB → IPA',
    heroTitle: 'Sources iOS. Catalogue. Outils.', heroDesc: 'Un catalogue vivant de sources vérifiées pour AltStore, SideStore et LiveContainer. Filtrez par type et contenu, combinez les sources compatibles et utilisez des outils iOS directement dans le navigateur.',
    availableSources: 'sources disponibles', mixReadySources: 'sources compatibles Mix', discoveredApps: 'apps uniques trouvées',
    catalogTitle: 'Sources AltStore · SideStore · LiveContainer', catalogDesc: 'Seules les sources ayant réussi le dernier contrôle automatique de disponibilité et JSON sont affichées.',
    sourceType: 'Type de source', genre: 'Genre', search: 'Recherche', sort: 'Trier', sortName: 'Nom A–Z', sortAppsHigh: 'Apps : plus d’abord', sortAppsLow: 'Apps : moins d’abord', reportBug: 'Signaler un bug', selection: 'Sélection', all: 'Tout', official: 'Officiel', trusted: 'Fiable', community: 'Communauté', modified: 'Modifié',
    games: 'Jeux', emulators: 'Émulateurs', video: 'Vidéo', music: 'Musique', animeManga: 'Anime & Manga', social: 'Social', downloads: 'Téléchargements', sideloadTools: 'Outils Sideload', utilities: 'Utilitaires',
    searchPlaceholder: 'Rechercher des sources…', note: 'Remarque :', catalogNote: 'CaseyCZ iOS Hub ne réhéberge pas les fichiers IPA tiers. Le catalogue utilise les URL publiques d’origine et conserve les liens de téléchargement d’origine. Les sources externes peuvent changer à tout moment.',
    toolsTitle: 'Outils', toolsDesc: 'Utilitaires fonctionnant directement dans le navigateur sur iPhone, iPad, Mac et PC.', readySourcesTitle: 'Sources prêtes', readySourcesDesc: 'Utilisez une source CaseyCZ prête ou ouvrez le Custom Builder autonome pour créer votre propre Mix filtré.', customBuilderCardTitle: 'Custom Builder', customBuilderCardDesc: 'Filtrez les sources vérifiées, choisissez n’importe quelle combinaison et créez votre propre CaseyCZ Mix sur une page dédiée.', openBuilder: 'Ouvrir le Builder', converterCardTitle: 'Convertisseur DEB → IPA', converterCardDesc: 'Convertissez un paquet iOS .deb compatible en .ipa localement dans le navigateur. Les paquets avec des métadonnées de système de fichiers spéciales peuvent encore nécessiter un outil de bureau.', openTool: 'Ouvrir l’outil',
    supportEyebrow: 'SOUTENIR CASEYCZ', supportTitle: 'Soutenir le développement.', supportDesc: 'Si CaseyCZ iOS Hub vous est utile, vous pouvez soutenir le développement via Buy Me a Coffee.', openCoffee: 'Ouvrir Buy Me a Coffee ↗',
    nothingFound: 'Aucun résultat', tryFilters: 'Essayez un autre type, genre ou terme de recherche.', online: 'En ligne', apps: 'apps', checked: 'Vérifié', showApps: 'Afficher les apps incluses', noApps: 'Aucune app n’est listée dans cette source.', add: '＋ Ajouter', copied: 'Copié.', sourceCopied: 'URL de la source copiée.', copyUrl: 'Copier URL', catalogLoadError: 'Impossible de charger le catalogue.',
    converterIntro: 'Convertissez une application iOS de .deb vers .ipa directement dans le navigateur. Fonctionne sur Windows, macOS et iPhone — le fichier n’est jamais envoyé.', local100: '100 % local', noUpload: 'Aucun envoi', chooseDeb: 'Choisir un fichier .deb', chooseDebHelp: 'Il doit contenir une véritable application iOS .app.', dropDeb: 'Déposez le .deb ici', tapChoose: 'ou touchez pour choisir un fichier', largeIphone: 'Fichier volumineux sur iPhone :', largeIphoneDesc: 'Safari dispose d’une mémoire limitée. Les très gros .deb peuvent être plus fiables sur Mac ou PC.', convertToIpa: 'Convertir en IPA', preparing: 'Préparation de la conversion…', done: 'TERMINÉ', downloadIpa: 'Télécharger IPA', shareIpa: 'Partager IPA', convertAnother: 'Convertir un autre', conversionFailed: 'Échec de la conversion', tryAgain: 'Réessayer', whatWebDoes: 'Ce que fait l’outil', stepDeb: 'Ouvre le paquet Debian .deb / AR.', stepData: 'Trouve data.tar et la véritable .app.', stepPayload: 'Crée Payload/App.app.', stepIpa: 'Emballe le résultat en .ipa.', important: 'Important :', importantDesc: 'Seuls les .deb contenant une .app peuvent être convertis. Les tweaks, bibliothèques et paquets système ne deviennent pas des IPA par simple reconditionnement.', signing: 'Signature :', signingDesc: 'L’IPA obtenue n’est pas signée automatiquement. Installez-la ensuite avec AltStore, SideStore, LiveContainer ou un autre installateur compatible.', loadingEngine: 'Chargement du moteur de conversion…', engineReady: 'Moteur de conversion prêt.', openingDeb: 'Ouverture du DEB…', extractingDeb: 'Extraction du paquet Debian…', dataFound: 'Archive de données trouvée…', lookingApp: 'Recherche de l’application iOS…', buildingPayload: 'Création du Payload…', packagingIpa: 'Création de l’IPA…', packagingWait: 'Cela peut prendre un moment pour une grosse app.', processedLocal: 'traité localement', appFiles: 'fichiers de l’app', files: 'fichiers', shareFailed: 'Échec du partage.', chooseDebToast: 'Choisissez un fichier .deb.', debInvalid: 'Le paquet ne ressemble pas à un .deb Debian standard — data.tar.* est introuvable.', appNotFound: 'Aucune .app iOS trouvée. Les tweaks, bibliothèques et autres paquets Debian ne peuvent pas être convertis en IPA.'
  }
};

export function normalizeLanguage(value) {
  return SUPPORTED_LANGUAGES.includes(value) ? value : 'en';
}

export function t(lang, key) {
  const current = messages[normalizeLanguage(lang)] || messages.en;
  return current[key] ?? messages.en[key] ?? key;
}

export function applyTranslations(lang, scope = document) {
  const current = normalizeLanguage(lang);
  scope.querySelectorAll('[data-i18n]').forEach(node => {
    node.textContent = t(current, node.dataset.i18n);
  });
  scope.querySelectorAll('[data-i18n-placeholder]').forEach(node => {
    node.placeholder = t(current, node.dataset.i18nPlaceholder);
  });
  scope.querySelectorAll('[data-i18n-title]').forEach(node => {
    node.title = t(current, node.dataset.i18nTitle);
  });
  scope.querySelectorAll('[data-i18n-aria-label]').forEach(node => {
    node.setAttribute('aria-label', t(current, node.dataset.i18nAriaLabel));
  });
}
